apiVersion: batch/v1
kind: Job
metadata:
  name: read-file-job
spec:
  template:
    spec:
      containers:
      - name: file-reader
        image: busybox  
        command: ["/bin/sh", "-c"]
        args:
          - while true; do
              cat /data/shared/yes.txt;  
              sleep 5;  
            done;
        volumeMounts:
        - name: shared-storage
          mountPath: /data/shared  
      restartPolicy: Never
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc
